version: '3'
services:
  app:
    build: .
    volumes:
     - .:/code
    depends_on:
      - mariadb
  mariadb:
    image: "mariadb:latest"
    environment: 
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    ports: 
      - "3306:3306"